export { default as Admin } from './Admin'
export { default as Home } from './Home'
export { default as Room } from './Room'
export { default as Rooms } from './Rooms'
export { default as Create } from './Create'
export { default as Register } from './Register'
export { default as Login } from './Login'
